export const DEMO_MODE = true;
export const DEMO_DATA_VERSION = 17;
export const STORAGE_KEY = "global-logistic-gl2-core-engine-v9";

export const Roles = Object.freeze({
  PLATFORM_OWNER: "platform_owner",
  GL_OPERATOR: "gl_operator",
  ADMIN_FINANCE: "admin_finance",
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  CLIENT_OWNER: "client_owner",
  CLIENT_DISPATCHER: "client_dispatcher",
  WAREHOUSE_WORKER: "warehouse_worker",
  CARRIER_OWNER: "carrier_owner",
  CARRIER_DISPATCHER: "carrier_dispatcher",
  DRIVER: "driver",
  INSURANCE_PARTNER: "insurance_partner",
  PAYMENT_OPERATOR: "payment_operator",
  SECURITY: "security",
  SECURITY_GUARD: "security",
  CUSTOMS_AGENT: "customs_agent",
  AUTHORITY_USER: "authority_user",
  FERRY_OPERATOR: "ferry_operator",
  RAIL_OPERATOR: "rail_operator",
  WORKSHOP: "workshop",
  MOBILE_SERVICE: "mobile_service",
  ROADSIDE_ASSISTANCE: "roadside_assistance",
  ACADEMY_TEACHER: "academy_teacher",
  ACADEMY_STUDENT: "academy_student",
  COMPLIANCE: "compliance",
  SUPPORT_AGENT: "support_agent",
  READONLY_AUDITOR: "readonly_auditor"
});

export const RoleLabels = Object.freeze({
  [Roles.PLATFORM_OWNER]: "Właściciel platformy",
  [Roles.GL_OPERATOR]: "Operator GL",
  [Roles.ADMIN_FINANCE]: "Administrator finansowy",
  [Roles.SUPER_ADMIN]: "Superadministrator",
  [Roles.ADMIN]: "Administrator",
  [Roles.CLIENT_OWNER]: "Właściciel klienta",
  [Roles.CLIENT_DISPATCHER]: "Dyspozytor klienta",
  [Roles.WAREHOUSE_WORKER]: "Pracownik magazynu",
  [Roles.CARRIER_OWNER]: "Właściciel przewoźnika",
  [Roles.CARRIER_DISPATCHER]: "Dyspozytor przewoźnika",
  [Roles.DRIVER]: "Kierowca",
  [Roles.INSURANCE_PARTNER]: "Partner ubezpieczeniowy",
  [Roles.PAYMENT_OPERATOR]: "Operator płatności",
  [Roles.SECURITY]: "Ochrona / brama",
  [Roles.CUSTOMS_AGENT]: "Agent celny",
  [Roles.AUTHORITY_USER]: "Organ kontrolny",
  [Roles.FERRY_OPERATOR]: "Operator promowy",
  [Roles.RAIL_OPERATOR]: "Operator kolejowy",
  [Roles.WORKSHOP]: "Warsztat",
  [Roles.MOBILE_SERVICE]: "Serwis mobilny",
  [Roles.ROADSIDE_ASSISTANCE]: "Pomoc drogowa",
  [Roles.ACADEMY_TEACHER]: "Nauczyciel Akademii GL",
  [Roles.ACADEMY_STUDENT]: "Student Akademii GL",
  [Roles.COMPLIANCE]: "Zgodnosc",
  [Roles.SUPPORT_AGENT]: "Wsparcie",
  [Roles.READONLY_AUDITOR]: "Audytor tylko do odczytu"
});

export const AuthoritySubtypes = Object.freeze({
  POLICE: "police",
  TRANSPORT_INSPECTION: "transport_inspection",
  CUSTOMS_AUTHORITY: "customs_authority",
  ROAD_AUTHORITY: "road_authority"
});

export const CompanyTypes = Object.freeze({
  CARRIER: "carrier",
  CLIENT: "client",
  WAREHOUSE: "warehouse",
  WORKSHOP: "workshop",
  INSURER: "insurer",
  INSURANCE: "insurance",
  DISPATCHER: "dispatcher",
  ACADEMY_PARTNER: "academy_partner",
  PAYMENT: "payment",
  SECURITY: "security",
  CUSTOMS_AGENT: "customs_agent",
  AUTHORITY: "authority",
  FERRY_OPERATOR: "ferry_operator",
  RAIL_OPERATOR: "rail_operator",
  MOBILE_SERVICE: "mobile_service",
  ROADSIDE_ASSISTANCE: "roadside_assistance"
});

export const CompanyVerificationStatuses = Object.freeze({
  DRAFT: "draft",
  PENDING: "pending",
  VERIFIED: "verified",
  LIMITED: "limited",
  SUSPENDED: "suspended",
  REJECTED: "rejected"
});

export const CompanyRoleNames = Object.freeze({
  OWNER: "owner",
  ADMIN: "admin",
  FINANCE: "finance",
  DISPATCHER: "dispatcher",
  DRIVER_MANAGER: "driver_manager",
  DRIVER: "driver",
  FLEET_MANAGER: "fleet_manager",
  CARRIER_ACCOUNTANT: "carrier_accountant",
  COMPANY_EMPLOYEE: "company_employee",
  WAREHOUSE_MANAGER: "warehouse_manager",
  MECHANIC: "mechanic",
  INSURANCE_MANAGER: "insurance_manager",
  EMPLOYEE: "employee",
  VIEWER: "viewer"
});

export const CompanyRoleLabels = Object.freeze({
  [CompanyRoleNames.OWNER]: "właściciel",
  [CompanyRoleNames.ADMIN]: "administrator",
  [CompanyRoleNames.FINANCE]: "finanse",
  [CompanyRoleNames.DISPATCHER]: "dyspozytor",
  [CompanyRoleNames.DRIVER_MANAGER]: "koordynator kierowców",
  [CompanyRoleNames.DRIVER]: "kierowca",
  [CompanyRoleNames.FLEET_MANAGER]: "manager floty",
  [CompanyRoleNames.CARRIER_ACCOUNTANT]: "ksiegowosc",
  [CompanyRoleNames.COMPANY_EMPLOYEE]: "pracownik administracyjny",
  [CompanyRoleNames.WAREHOUSE_MANAGER]: "magazyn",
  [CompanyRoleNames.MECHANIC]: "serwis",
  [CompanyRoleNames.INSURANCE_MANAGER]: "ubezpieczenia",
  [CompanyRoleNames.EMPLOYEE]: "pracownik",
  [CompanyRoleNames.VIEWER]: "podgląd"
});

export const KnowledgeSourceTypes = Object.freeze({
  PROFESSIONAL_COMPETENCE_CERTIFICATE: "professional_competence_certificate",
  CARRIER_LICENSE: "carrier_license",
  CMR_CONVENTION: "cmr_convention",
  ADR_REGULATION: "adr_regulation",
  MOBILITY_PACKAGE: "mobility_package",
  DRIVER_WORK_TIME: "driver_work_time",
  TACHOGRAPH_RULES: "tachograph_rules",
  INSURANCE_RULES: "insurance_rules",
  CUSTOMS_RULES: "customs_rules",
  WAREHOUSE_PROCEDURE: "warehouse_procedure",
  GL_INTERNAL_POLICY: "gl_internal_policy",
  ACADEMY_MATERIAL: "academy_material",
  LEGAL_UPDATE: "legal_update",
  TEST_QUESTION_BANK: "test_question_bank",
  TRAINING_MODULE: "training_module",
  CERTIFICATION_PATH: "certification_path"
});

export const CustomsDocumentTypes = Object.freeze([
  "sad",
  "t1",
  "ex",
  "mrn",
  "commercial_invoice",
  "packing_list",
  "certificate_of_origin"
]);

export const AuthorityDocumentTypes = Object.freeze([
  "cmr",
  "transport_license",
  "road_permit",
  "certificate",
  "legal_required_document",
  "insurance_policy"
]);

export const FerryDocumentTypes = Object.freeze([
  "ferry_ticket",
  "booking_confirmation",
  "boarding_confirmation"
]);

export const AccountStatuses = Object.freeze({
  DRAFT: "draft",
  PHONE_VERIFIED: "phone_verified",
  IDENTITY_PENDING: "identity_pending",
  IDENTITY_VERIFIED: "identity_verified",
  ROLE_DOCUMENTS_PENDING: "role_documents_pending",
  COMPANY_PENDING: "company_pending",
  APPROVED: "approved",
  LIMITED: "limited",
  PENDING: "draft",
  VERIFIED: "approved",
  SUSPENDED: "suspended",
  REJECTED: "rejected",
  BLOCKED: "suspended"
});

export const TransportStatuses = Object.freeze({
  DRAFT: "draft",
  PENDING_WAREHOUSE_PHOTO: "pending_warehouse_photo",
  READY_TO_PUBLISH: "ready_to_publish",
  PUBLISHED: "published",
  CARRIER_OFFER_RECEIVED: "carrier_offer_received",
  CARRIER_ACCEPTED: "carrier_accepted",
  DRIVER_ASSIGNED: "driver_assigned",
  PICKUP_NAVIGATION_STARTED: "pickup_navigation_started",
  ARRIVED_AT_PICKUP: "arrived_at_pickup",
  LOADING_STARTED: "loading_started",
  LOADING_CONFIRMED: "loading_confirmed",
  PICKUP_DOCUMENTS_UPLOADED: "pickup_documents_uploaded",
  IN_TRANSIT: "in_transit",
  PARKING_BREAK: "parking_break",
  CUSTOMS_REQUIRED: "customs_required",
  WAITING_FOR_CUSTOMS: "waiting_for_customs",
  CUSTOMS_IN_PROGRESS: "customs_in_progress",
  CUSTOMS_CLEARED: "customs_cleared",
  CUSTOMS_HOLD: "customs_hold",
  CONTROL_STARTED: "control_started",
  DOCUMENT_CHECK: "document_check",
  ROAD_INSPECTION: "road_inspection",
  CONTROL_PASSED: "control_passed",
  CONTROL_ISSUE_FOUND: "control_issue_found",
  ARRIVED_AT_DELIVERY: "arrived_at_delivery",
  UNLOADING_STARTED: "unloading_started",
  DELIVERY_CONFIRMED: "delivery_confirmed",
  DELIVERY_DOCUMENTS_UPLOADED: "delivery_documents_uploaded",
  INVOICE_PENDING: "invoice_pending",
  PAYMENT_PENDING: "payment_pending",
  PAID: "paid",
  FERRY_REQUIRED: "ferry_required",
  FERRY_BOOKED: "ferry_booked",
  GOING_TO_PORT: "going_to_port",
  WAITING_FOR_FERRY: "waiting_for_ferry",
  CHECKED_IN_FERRY: "checked_in_ferry",
  BOARDING: "boarding",
  ON_FERRY: "on_ferry",
  LEAVING_FERRY: "leaving_ferry",
  FERRY_COMPLETED: "ferry_completed",
  CONTINUE_ROAD_TRANSPORT: "continue_road_transport",
  COMPLETED: "completed",
  DISPUTE_OPENED: "dispute_opened",
  CLAIM_OPENED: "claim_opened",
  CANCELLED: "cancelled",
  BLOCKED: "blocked"
});

export const TransportModes = Object.freeze({
  ROAD: "ROAD",
  FERRY: "FERRY",
  TRAIN: "TRAIN",
  INTERMODAL: "INTERMODAL"
});

export const PaymentStatuses = Object.freeze({
  NOT_REQUIRED: "payment_not_required",
  PENDING: "payment_pending",
  RESERVED: "payment_reserved",
  BLOCKED: "payment_blocked",
  RELEASED: "payment_released",
  FAILED: "payment_failed",
  REFUNDED: "payment_refunded"
});

export const ActionTypes = Object.freeze({
  SELECT_LANGUAGE: "SELECT_LANGUAGE",
  OPEN_LANGUAGE_SELECTION: "OPEN_LANGUAGE_SELECTION",
  RETURN_TO_START: "RETURN_TO_START",
  SELECT_CONTEXT: "SELECT_CONTEXT",
  SELECT_ROLE: "SELECT_ROLE",
  SELECT_VIEW: "SELECT_VIEW",
  SELECT_TRANSPORT: "SELECT_TRANSPORT",
  CREATE_COMPANY: "CREATE_COMPANY",
  UPDATE_COMPANY: "UPDATE_COMPANY",
  INVITE_COMPANY_USER: "INVITE_COMPANY_USER",
  HIRE_COMPANY_EMPLOYEE: "HIRE_COMPANY_EMPLOYEE",
  ACCEPT_COMPANY_INVITATION: "ACCEPT_COMPANY_INVITATION",
  CHANGE_COMPANY_USER_ROLE: "CHANGE_COMPANY_USER_ROLE",
  CHANGE_COMPANY_USER_PERMISSIONS: "CHANGE_COMPANY_USER_PERMISSIONS",
  REMOVE_COMPANY_USER: "REMOVE_COMPANY_USER",
  UPLOAD_COMPANY_DOCUMENT: "UPLOAD_COMPANY_DOCUMENT",
  VERIFY_COMPANY: "VERIFY_COMPANY",
  REJECT_COMPANY_VERIFICATION: "REJECT_COMPANY_VERIFICATION",
  SUSPEND_COMPANY: "SUSPEND_COMPANY",
  REGISTER_USER: "REGISTER_USER",
  VERIFY_ACCOUNT: "VERIFY_ACCOUNT",
  CHANGE_PHONE: "CHANGE_PHONE",
  AUTH_LOGIN_START: "AUTH_LOGIN_START",
  AUTH_LOGIN_VERIFY_OTP: "AUTH_LOGIN_VERIFY_OTP",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_PASSWORD_RESET_START: "AUTH_PASSWORD_RESET_START",
  AUTH_PASSWORD_RESET_CONFIRM: "AUTH_PASSWORD_RESET_CONFIRM",
  ONBOARDING_START: "ONBOARDING_START",
  ONBOARDING_VERIFY_PHONE: "ONBOARDING_VERIFY_PHONE",
  ONBOARDING_CREATE_ACCOUNT: "ONBOARDING_CREATE_ACCOUNT",
  ONBOARDING_SELECT_ROLE: "ONBOARDING_SELECT_ROLE",
  ONBOARDING_SUBMIT_IDENTITY: "ONBOARDING_SUBMIT_IDENTITY",
  ONBOARDING_SUBMIT_ROLE_DOCUMENTS: "ONBOARDING_SUBMIT_ROLE_DOCUMENTS",
  ONBOARDING_SUBMIT_COMPANY: "ONBOARDING_SUBMIT_COMPANY",
  ONBOARDING_APPROVE: "ONBOARDING_APPROVE",
  ONBOARDING_REJECT: "ONBOARDING_REJECT",
  ADD_COMPANY_DRIVER: "ADD_COMPANY_DRIVER",
  ADD_VEHICLE: "ADD_VEHICLE",
  CREATE_KNOWLEDGE_SOURCE: "CREATE_KNOWLEDGE_SOURCE",
  UPDATE_KNOWLEDGE_SOURCE: "UPDATE_KNOWLEDGE_SOURCE",
  ARCHIVE_KNOWLEDGE_SOURCE: "ARCHIVE_KNOWLEDGE_SOURCE",
  CREATE_LOAD: "CREATE_LOAD",
  ADD_LOAD_PHOTO: "ADD_LOAD_PHOTO",
  CONFIRM_GPS: "CONFIRM_GPS",
  PUBLISH_LOAD: "PUBLISH_LOAD",
  ACCEPT_CARRIER: "ACCEPT_CARRIER",
  ASSIGN_DRIVER: "ASSIGN_DRIVER",
  START_PICKUP_NAVIGATION: "START_PICKUP_NAVIGATION",
  ARRIVE_PICKUP: "ARRIVE_PICKUP",
  START_LOADING: "START_LOADING",
  CONFIRM_LOADING: "CONFIRM_LOADING",
  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  START_TRANSIT: "START_TRANSIT",
  SELECT_PARKING: "SELECT_PARKING",
  IMPORT_DDD: "IMPORT_DDD",
  START_BREAK: "START_BREAK",
  FINISH_BREAK: "FINISH_BREAK",
  ARRIVE_DELIVERY: "ARRIVE_DELIVERY",
  START_UNLOADING: "START_UNLOADING",
  CONFIRM_DELIVERY: "CONFIRM_DELIVERY",
  RELEASE_PAYMENT: "RELEASE_PAYMENT",
  OPEN_DISPUTE: "OPEN_DISPUTE",
  OPEN_CLAIM: "OPEN_CLAIM",
  SEND_MESSAGE: "SEND_MESSAGE",
  REQUEST_TRANSLATION: "REQUEST_TRANSLATION",
  SCAN_LICENSE_PLATE: "SCAN_LICENSE_PLATE",
  RECORD_SECURITY_CHECK: "RECORD_SECURITY_CHECK",
  MARK_CUSTOMS_REQUIRED: "MARK_CUSTOMS_REQUIRED",
  SEND_TO_CUSTOMS: "SEND_TO_CUSTOMS",
  START_CUSTOMS: "START_CUSTOMS",
  CLEAR_CUSTOMS: "CLEAR_CUSTOMS",
  HOLD_CUSTOMS: "HOLD_CUSTOMS",
  START_AUTHORITY_CONTROL: "START_AUTHORITY_CONTROL",
  RECORD_DOCUMENT_CHECK: "RECORD_DOCUMENT_CHECK",
  RECORD_ROAD_INSPECTION: "RECORD_ROAD_INSPECTION",
  PASS_AUTHORITY_CONTROL: "PASS_AUTHORITY_CONTROL",
  REPORT_AUTHORITY_ISSUE: "REPORT_AUTHORITY_ISSUE",
  MARK_FERRY_REQUIRED: "MARK_FERRY_REQUIRED",
  BOOK_FERRY: "BOOK_FERRY",
  START_PORT_NAVIGATION: "START_PORT_NAVIGATION",
  CHECK_IN_FERRY: "CHECK_IN_FERRY",
  BOARD_FERRY: "BOARD_FERRY",
  COMPLETE_FERRY: "COMPLETE_FERRY",
  REPORT_BREAKDOWN: "REPORT_BREAKDOWN",
  REQUEST_TECHNICAL_SERVICE: "REQUEST_TECHNICAL_SERVICE",
  ACCEPT_SERVICE_JOB: "ACCEPT_SERVICE_JOB",
  COMPLETE_SERVICE_JOB: "COMPLETE_SERVICE_JOB",
  SIMULATE_API_CALL: "SIMULATE_API_CALL",
  RUN_INTEGRATION_SYNC: "RUN_INTEGRATION_SYNC",
  RUN_RESILIENCE_CHECK: "RUN_RESILIENCE_CHECK",
  RUN_COMPLIANCE_CHECK: "RUN_COMPLIANCE_CHECK",
  AI_RUN_CHECK: "AI_RUN_CHECK",
  ADMIN_BLOCK_TRANSPORT: "ADMIN_BLOCK_TRANSPORT",
  ADMIN_RESOLVE_DISPUTE: "ADMIN_RESOLVE_DISPUTE",
  ADMIN_BLOCK_ACCOUNT: "ADMIN_BLOCK_ACCOUNT",
  PARKING_REPORT: "PARKING_REPORT",
  RESET_DEMO: "RESET_DEMO"
});

export const EventTypes = Object.freeze({
  ACTION_BLOCKED: "ACTION_BLOCKED",
  SESSION_CONTEXT_CHANGED: "SESSION_CONTEXT_CHANGED",
  SESSION_ROLE_CHANGED: "SESSION_ROLE_CHANGED",
  UI_VIEW_CHANGED: "UI_VIEW_CHANGED",
  COMPANY_CREATED: "COMPANY_CREATED",
  COMPANY_UPDATED: "COMPANY_UPDATED",
  COMPANY_DOCUMENT_UPLOADED: "COMPANY_DOCUMENT_UPLOADED",
  COMPANY_USER_INVITED: "COMPANY_USER_INVITED",
  COMPANY_EMPLOYEE_HIRED: "COMPANY_EMPLOYEE_HIRED",
  COMPANY_INVITATION_ACCEPTED: "COMPANY_INVITATION_ACCEPTED",
  COMPANY_USER_ROLE_CHANGED: "COMPANY_USER_ROLE_CHANGED",
  COMPANY_USER_PERMISSIONS_CHANGED: "COMPANY_USER_PERMISSIONS_CHANGED",
  COMPANY_USER_REMOVED: "COMPANY_USER_REMOVED",
  COMPANY_SUSPENDED: "COMPANY_SUSPENDED",
  COMPANY_VERIFICATION_REJECTED: "COMPANY_VERIFICATION_REJECTED",
  USER_REGISTERED: "USER_REGISTERED",
  ACCOUNT_VERIFIED: "ACCOUNT_VERIFIED",
  PHONE_CHANGED: "PHONE_CHANGED",
  ACCOUNT_BLOCKED: "ACCOUNT_BLOCKED",
  AUTH_OTP_CHALLENGE_CREATED: "AUTH_OTP_CHALLENGE_CREATED",
  AUTH_OTP_FAILED: "AUTH_OTP_FAILED",
  AUTH_OTP_LOCKED: "AUTH_OTP_LOCKED",
  AUTH_LOGIN_SUCCEEDED: "AUTH_LOGIN_SUCCEEDED",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGGED_OUT: "AUTH_LOGGED_OUT",
  AUTH_PASSWORD_RESET_REQUESTED: "AUTH_PASSWORD_RESET_REQUESTED",
  AUTH_PASSWORD_RESET_SUCCEEDED: "AUTH_PASSWORD_RESET_SUCCEEDED",
  ONBOARDING_STARTED: "ONBOARDING_STARTED",
  ONBOARDING_LANGUAGE_SELECTED: "ONBOARDING_LANGUAGE_SELECTED",
  PHONE_ADDED: "PHONE_ADDED",
  PHONE_OTP_VERIFIED: "PHONE_OTP_VERIFIED",
  USER_ACCOUNT_CREATED: "USER_ACCOUNT_CREATED",
  ROLE_VERIFICATION_STARTED: "ROLE_VERIFICATION_STARTED",
  IDENTITY_DOCUMENT_SUBMITTED: "IDENTITY_DOCUMENT_SUBMITTED",
  IDENTITY_VERIFIED: "IDENTITY_VERIFIED",
  ROLE_DOCUMENTS_SUBMITTED: "ROLE_DOCUMENTS_SUBMITTED",
  COMPANY_PROFILE_SUBMITTED: "COMPANY_PROFILE_SUBMITTED",
  ONBOARDING_APPROVED: "ONBOARDING_APPROVED",
  ONBOARDING_REJECTED: "ONBOARDING_REJECTED",
  DOCUMENT_REJECTED: "DOCUMENT_REJECTED",
  COMPLIANCE_SIGNAL_RECORDED: "COMPLIANCE_SIGNAL_RECORDED",
  COMPANY_VERIFIED: "COMPANY_VERIFIED",
  KNOWLEDGE_SOURCE_CREATED: "KNOWLEDGE_SOURCE_CREATED",
  KNOWLEDGE_SOURCE_UPDATED: "KNOWLEDGE_SOURCE_UPDATED",
  KNOWLEDGE_SOURCE_ARCHIVED: "KNOWLEDGE_SOURCE_ARCHIVED",
  LOAD_CREATED: "LOAD_CREATED",
  LOAD_PHOTO_ADDED: "LOAD_PHOTO_ADDED",
  LOAD_PUBLISHED: "LOAD_PUBLISHED",
  CARRIER_ACCEPTED: "CARRIER_ACCEPTED",
  COMPANY_DRIVER_ADDED: "COMPANY_DRIVER_ADDED",
  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
  GPS_COORDINATES_CONFIRMED: "GPS_COORDINATES_CONFIRMED",
  DRIVER_ARRIVED_PICKUP: "DRIVER_ARRIVED_PICKUP",
  LOADING_STARTED: "LOADING_STARTED",
  LOADING_CONFIRMED: "LOADING_CONFIRMED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  TRANSPORT_IN_TRANSIT: "TRANSPORT_IN_TRANSIT",
  PARKING_SELECTED: "PARKING_SELECTED",
  TACHOGRAPH_IMPORTED: "TACHOGRAPH_IMPORTED",
  BREAK_STARTED: "BREAK_STARTED",
  BREAK_FINISHED: "BREAK_FINISHED",
  DELIVERY_CONFIRMED: "DELIVERY_CONFIRMED",
  PAYMENT_RELEASED: "PAYMENT_RELEASED",
  TRANSPORT_COMPLETED: "TRANSPORT_COMPLETED",
  DISPUTE_OPENED: "DISPUTE_OPENED",
  DISPUTE_RESOLVED: "DISPUTE_RESOLVED",
  CLAIM_OPENED: "CLAIM_OPENED",
  TRUST_SCORE_CHANGED: "TRUST_SCORE_CHANGED",
  AI_ALERT_CREATED: "AI_ALERT_CREATED",
  TRANSPORT_BLOCKED: "TRANSPORT_BLOCKED",
  SHIPMENT_CREATED: "SHIPMENT_CREATED",
  SHIPMENT_UPDATED: "SHIPMENT_UPDATED",
  WALLET_HOLD_CREATED: "WALLET_HOLD_CREATED",
  WALLET_HOLD_RELEASED: "WALLET_HOLD_RELEASED",
  WALLET_CREDITED: "WALLET_CREDITED",
  ESCROW_RESERVED: "ESCROW_RESERVED",
  ESCROW_BLOCKED: "ESCROW_BLOCKED",
  ESCROW_RELEASED: "ESCROW_RELEASED",
  PLATFORM_FEE_RECORDED: "PLATFORM_FEE_RECORDED",
  JOB_CREATED: "JOB_CREATED",
  JOB_COMPLETED: "JOB_COMPLETED",
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_TRANSLATED: "MESSAGE_TRANSLATED",
  LICENSE_PLATE_IDENTIFIED: "LICENSE_PLATE_IDENTIFIED",
  PLATE_CHAT_CREATED: "PLATE_CHAT_CREATED",
  SECURITY_CHECK_RECORDED: "SECURITY_CHECK_RECORDED",
  SECURITY_GATE_DENIED: "SECURITY_GATE_DENIED",
  CUSTOMS_REQUIRED_RECORDED: "CUSTOMS_REQUIRED_RECORDED",
  CUSTOMS_WAITING: "CUSTOMS_WAITING",
  CUSTOMS_STARTED: "CUSTOMS_STARTED",
  CUSTOMS_CLEARED: "CUSTOMS_CLEARED",
  CUSTOMS_HOLD_PLACED: "CUSTOMS_HOLD_PLACED",
  CUSTOMS_PAYMENT_SIMULATED: "CUSTOMS_PAYMENT_SIMULATED",
  CUSTOMS_DOCUMENT_RECEIVED: "CUSTOMS_DOCUMENT_RECEIVED",
  AUTHORITY_CONTROL_STARTED: "AUTHORITY_CONTROL_STARTED",
  AUTHORITY_DOCUMENT_CHECKED: "AUTHORITY_DOCUMENT_CHECKED",
  AUTHORITY_ROAD_INSPECTION_DONE: "AUTHORITY_ROAD_INSPECTION_DONE",
  AUTHORITY_CONTROL_PASSED: "AUTHORITY_CONTROL_PASSED",
  AUTHORITY_ISSUE_FOUND: "AUTHORITY_ISSUE_FOUND",
  AUTHORITY_ACCESS_RECORDED: "AUTHORITY_ACCESS_RECORDED",
  FERRY_REQUIRED_RECORDED: "FERRY_REQUIRED_RECORDED",
  FERRY_BOOKED: "FERRY_BOOKED",
  FERRY_GOING_TO_PORT: "FERRY_GOING_TO_PORT",
  FERRY_CHECKED_IN: "FERRY_CHECKED_IN",
  FERRY_BOARDING: "FERRY_BOARDING",
  FERRY_ONBOARD: "FERRY_ONBOARD",
  FERRY_COMPLETED: "FERRY_COMPLETED",
  FERRY_ETA_UPDATED: "FERRY_ETA_UPDATED",
  FERRY_PAYMENT_SIMULATED: "FERRY_PAYMENT_SIMULATED",
  SERVICE_BREAKDOWN_REPORTED: "SERVICE_BREAKDOWN_REPORTED",
  SERVICE_PROVIDER_SELECTED: "SERVICE_PROVIDER_SELECTED",
  SERVICE_ACCEPTED: "SERVICE_ACCEPTED",
  SERVICE_COMPLETED: "SERVICE_COMPLETED",
  SERVICE_ETA_UPDATED: "SERVICE_ETA_UPDATED",
  SERVICE_PAYMENT_SIMULATED: "SERVICE_PAYMENT_SIMULATED",
  API_CALL_RECORDED: "API_CALL_RECORDED",
  API_RATE_LIMIT_FLAGGED: "API_RATE_LIMIT_FLAGGED",
  INTEGRATION_SYNC_COMPLETED: "INTEGRATION_SYNC_COMPLETED",
  INTEGRATION_SYNC_BLOCKED: "INTEGRATION_SYNC_BLOCKED",
  RESILIENCE_CHECK_COMPLETED: "RESILIENCE_CHECK_COMPLETED",
  EMERGENCY_MODE_READY: "EMERGENCY_MODE_READY",
  COMPLIANCE_CHECK_COMPLETED: "COMPLIANCE_CHECK_COMPLETED",
  COMPLIANCE_CHECK_BLOCKED: "COMPLIANCE_CHECK_BLOCKED",
  DOCUMENT_CONFIRMED: "DOCUMENT_CONFIRMED",
  DIGITAL_CMR_CREATED: "DIGITAL_CMR_CREATED",
  DIGITAL_CMR_LOCKED: "DIGITAL_CMR_LOCKED",
  DISPUTE_EVIDENCE_PACK_CREATED: "DISPUTE_EVIDENCE_PACK_CREATED",
  INSURANCE_RISK_CLOSED: "INSURANCE_RISK_CLOSED",
  DEMO_RESET: "DEMO_RESET",
  PAYLOAD_PARSE_ERROR: "PAYLOAD_PARSE_ERROR"
});

export const SourceTypes = Object.freeze({
  USER: "user",
  SYSTEM: "system",
  AI: "AI"
});

export const CriticalTransportActions = new Set([
  ActionTypes.PUBLISH_LOAD,
  ActionTypes.ACCEPT_CARRIER,
  ActionTypes.ASSIGN_DRIVER,
  ActionTypes.START_PICKUP_NAVIGATION,
  ActionTypes.ARRIVE_PICKUP,
  ActionTypes.START_LOADING,
  ActionTypes.CONFIRM_LOADING,
  ActionTypes.START_TRANSIT,
  ActionTypes.ARRIVE_DELIVERY,
  ActionTypes.START_UNLOADING,
  ActionTypes.CONFIRM_DELIVERY,
  ActionTypes.RELEASE_PAYMENT,
  ActionTypes.MARK_CUSTOMS_REQUIRED,
  ActionTypes.SEND_TO_CUSTOMS,
  ActionTypes.START_CUSTOMS,
  ActionTypes.CLEAR_CUSTOMS,
  ActionTypes.HOLD_CUSTOMS,
  ActionTypes.START_AUTHORITY_CONTROL,
  ActionTypes.RECORD_DOCUMENT_CHECK,
  ActionTypes.RECORD_ROAD_INSPECTION,
  ActionTypes.PASS_AUTHORITY_CONTROL,
  ActionTypes.REPORT_AUTHORITY_ISSUE,
  ActionTypes.MARK_FERRY_REQUIRED,
  ActionTypes.BOOK_FERRY,
  ActionTypes.START_PORT_NAVIGATION,
  ActionTypes.CHECK_IN_FERRY,
  ActionTypes.BOARD_FERRY,
  ActionTypes.COMPLETE_FERRY,
  ActionTypes.REPORT_BREAKDOWN,
  ActionTypes.REQUEST_TECHNICAL_SERVICE,
  ActionTypes.ACCEPT_SERVICE_JOB,
  ActionTypes.COMPLETE_SERVICE_JOB
]);

export const StatusProgress = Object.freeze({
  [TransportStatuses.DRAFT]: 4,
  [TransportStatuses.PENDING_WAREHOUSE_PHOTO]: 8,
  [TransportStatuses.READY_TO_PUBLISH]: 14,
  [TransportStatuses.PUBLISHED]: 20,
  [TransportStatuses.CARRIER_ACCEPTED]: 30,
  [TransportStatuses.DRIVER_ASSIGNED]: 38,
  [TransportStatuses.PICKUP_NAVIGATION_STARTED]: 44,
  [TransportStatuses.ARRIVED_AT_PICKUP]: 50,
  [TransportStatuses.LOADING_STARTED]: 55,
  [TransportStatuses.LOADING_CONFIRMED]: 62,
  [TransportStatuses.PICKUP_DOCUMENTS_UPLOADED]: 66,
  [TransportStatuses.IN_TRANSIT]: 72,
  [TransportStatuses.PARKING_BREAK]: 74,
  [TransportStatuses.CUSTOMS_REQUIRED]: 73,
  [TransportStatuses.WAITING_FOR_CUSTOMS]: 74,
  [TransportStatuses.CUSTOMS_IN_PROGRESS]: 75,
  [TransportStatuses.CUSTOMS_CLEARED]: 78,
  [TransportStatuses.CUSTOMS_HOLD]: 70,
  [TransportStatuses.CONTROL_STARTED]: 74,
  [TransportStatuses.DOCUMENT_CHECK]: 75,
  [TransportStatuses.ROAD_INSPECTION]: 76,
  [TransportStatuses.CONTROL_PASSED]: 78,
  [TransportStatuses.CONTROL_ISSUE_FOUND]: 70,
  [TransportStatuses.ARRIVED_AT_DELIVERY]: 82,
  [TransportStatuses.UNLOADING_STARTED]: 86,
  [TransportStatuses.DELIVERY_CONFIRMED]: 91,
  [TransportStatuses.DELIVERY_DOCUMENTS_UPLOADED]: 94,
  [TransportStatuses.PAYMENT_PENDING]: 96,
  [TransportStatuses.PAID]: 98,
  [TransportStatuses.FERRY_REQUIRED]: 72,
  [TransportStatuses.FERRY_BOOKED]: 73,
  [TransportStatuses.GOING_TO_PORT]: 74,
  [TransportStatuses.WAITING_FOR_FERRY]: 75,
  [TransportStatuses.CHECKED_IN_FERRY]: 76,
  [TransportStatuses.BOARDING]: 77,
  [TransportStatuses.ON_FERRY]: 78,
  [TransportStatuses.LEAVING_FERRY]: 79,
  [TransportStatuses.FERRY_COMPLETED]: 80,
  [TransportStatuses.CONTINUE_ROAD_TRANSPORT]: 81,
  [TransportStatuses.COMPLETED]: 100,
  [TransportStatuses.DISPUTE_OPENED]: 70,
  [TransportStatuses.CLAIM_OPENED]: 70,
  [TransportStatuses.CANCELLED]: 100,
  [TransportStatuses.BLOCKED]: 40
});

export const NavItems = Object.freeze([
  { id: "dashboard", label: "Panel główny" },
  { id: "auth", label: "Logowanie/Rejestracja" },
  { id: "roles", label: "Przełącznik ról" },
  { id: "transports", label: "Lista transportów" },
  { id: "details", label: "Szczegóły transportu" },
  { id: "shipments", label: "Ładunki" },
  { id: "create", label: "Utwórz ładunek" },
  { id: "warehouse", label: "Zdjęcie magazynu" },
  { id: "carrier", label: "Akceptacja przewoźnika" },
  { id: "driver_assignment", label: "Przypisanie kierowcy" },
  { id: "gps", label: "Mapa GPS" },
  { id: "parking", label: "Parkingi na żywo" },
  { id: "documents", label: "Dokumenty" },
  { id: "payments", label: "Płatności" },
  { id: "wallets", label: "Portfele" },
  { id: "escrow", label: "Escrow" },
  { id: "revenue", label: "Przychody" },
  { id: "insurance", label: "Ubezpieczenia" },
  { id: "jobs", label: "Zlecenia pracy" },
  { id: "communication", label: "Komunikacja" },
  { id: "translations", label: "Tłumaczenia" },
  { id: "security", label: "Ochrona" },
  { id: "customs", label: "Cło" },
  { id: "authority", label: "Kontrola drogowa" },
  { id: "ferry", label: "Prom / intermodal" },
  { id: "service", label: "Serwis techniczny" },
  { id: "api", label: "API" },
  { id: "integrations", label: "Integracje" },
  { id: "compliance", label: "Zgodność" },
  { id: "resilience", label: "Odporność" },
  { id: "trust", label: "Reputacja" },
  { id: "ai", label: "Kontrola AI" },
  { id: "audit", label: "Dziennik audytu" },
  { id: "system_tests", label: "Testy systemu" },
  { id: "admin", label: "Panel admina" }
]);

export const AllRoles = [...new Set(Object.values(Roles))];
